### ISSUE TITLE
No support for instant payments?

### ISSUE THREAD

**Issue by thewhiterabbit** [CraftingStore/OxidePlugin#1]
I was just about to buy Silver plan 15 seconds ago, then I read that the instant payments you advertise as a feature of the Silver plan aren't supported for the OxidePlugin. Wow. Borderline false advertising.

When is this going to be supported?

Why is RCON supported for Minecraft, but not for Rust?

Why can't the OxidePlugin be sent payment notifications so it can add users to premium groups with your platform? The other paid platforms do this already.

I see this lack of instant payment support as a huge insult to prospective buyers of a paid product offering.

Fortunately I read past the purchase page to more details or I would have literally wasted money.

**Comment by Tim-NL** [comment]
Hi,

"I was just about to buy Silver plan 15 seconds ago, then I read that the instant payments you advertise as a feature of the Silver plan aren't supported for the OxidePlugin. Wow. Borderline false advertising."
It is not false advertisement, because you can click the (?) behind it for more information. Not all platforms can support it.

"When is this going to be supported?"
You can use our RCON integration for Rust if you want instant payment processing. It will take up to 5 minutes on Oxide due to the limitations of Oxide. For our Java plugin we can create many classes, include libraries and such. For Oxide we are limited to one file, so we cannot offer this ability. That is why we have described this in the article.

"Why is RCON supported for Minecraft, but not for Rust?"
RCON is supported for all games, including Rust.

"Why can't the OxidePlugin be sent payment notifications so it can add users to premium groups with your platform? The other paid platforms do this already."
It can, it can run commands, just like any of our other plugins.

"I see this lack of instant payment support as a huge insult to prospective buyers of a paid product offering."
It's not lacking, and our documentation clearly states that integrations support it. RCON does support, you can use that on Rust without any issues.

I hope this clears it up.

-Tim

**Comment by thewhiterabbit** [comment]
Everything I've read on your site explains how to setup this OxidePlugin for Rust, not an RCON connection. Setup explicitly tells users to install this plugin. Clicking the question icon in the premium signup page...

```
Realtime payments
Silver and gold stores will use our new real-time socket connection system to get instant (real-time) payments.

How does it work?
When you start the server, we'll set-up a real-time socket connection between your Minecraft server and CraftingStore.net. Instead of polling the CraftingStore API on set intervals, we'll send a message to your server when someone makes a payment. This way your server will poll the required commands from our API the second the donation gets though. 

How fast is this new system?
It depends on the payment providers, when PayPal, for example, confirms the payment, we'll send the message within 5 seconds. Most of them process the payment within 20 seconds. 

How do I enable this feature? 
It's enabled by default when you start the server, and we detect that it's premium the feature will be enabled.

**On what server types does it work?
Currently only on our Spigot, BungeeCord, Sponge and RCON server types. It does not work for uMod or Databases.**
```

[Setup Help](https://help.craftingstore.net/books/plugin-help/page/how-to-install-the-plugin)
The above link explicitly tells me that I need to install the umod plugin for Rust/Hurtworld
The premium plan features' information page tells me instant payment processing does not support your umod plugin.

So do I believe you, or the website information?

Paying for something that has contradictory information seems irrational.

I'll consider the premium CraftingStore plans when the public facing information reflects what you just told me here, with clear setup instructions for Rust RCON instant payments.

I don't see anything that backs up your claims in any of the instructions that are currently accessible through your setup or sales information.

**Comment by Tim-NL** [comment]
Hi,

We do indeed not have set-up instructions for RCON, as it's not CraftingStore specific. Our Java plugin is created by us, so we need to explain how it works. Just like the Oxide mod. But RCON something baked into many game servers (Rust, Minecraft, Hurtworld, Source games, etc.). It's not specific to us so we did not document it. 

The information you linked explains that Oxide is not one of the supported systems. And that is correct.

-Tim

**Comment by thewhiterabbit** [comment]
This is why CraftingStore is bottom tier:

> It's not practical to explain what platforms are supported right on the payment page. It would be a long explanation for every feature. That is why we have a question (?) icon behind them. So you can read what it is.

You say CraftingStore IPN to RCON is supported for Rust, then you outline how there's an information link...which tells server owners they should use a plugin that doesn't support the IPN features they are spending money to get for their Rust server.

Enjoy losing conversions, or realize your mistake and amend the (?) link to explain how to get IPN with RCON in Rust servers.

Meanwhile, I'll be using something much more powerful at the cost of slightly more of my time, with zero financial risk (something completely open source), because of the apparent low ROI of CraftingStore comparable products. Being a software engineer has it's perks.

Sorry I'm so blunt, that's just how I am. If you need help, ask. I might have time to write a brief tut for RCON IPN in RUST for your website. If that feature actually works already in your scripts.
